apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 # needs to match the containerr port in deployment.yaml
    #nodePort: #port that will be exposed on the node itself, by default it is assigned